package studio.codable.nestedrecyclerviewdemo

import studio.codable.nestedrecyclerviewdemo.model.Color
import studio.codable.nestedrecyclerviewdemo.model.Palette

fun getTestData(): List<Palette> =
    listOf(Palette(name = "Palette 1",
        colors = listOf(Color(id = 1,"Palatinate purple", "#5C2751"),
            Color(id = 2,"Liberty", "#6457A6"),
            Color(id = 3,"Maximum Blue Purple", "#9DACFF"),
            Color(id = 4,"Sky Blue Crayola", "#76E5FC"))),
        Palette(name = "Palette 2",
            colors = listOf(Color(id = 5,"Nyanza", "#DCEED1"),
                Color(id = 6,"Cambridge Blue", "#AAC0AA"),
                Color(id = 7,"Old Lavender", "#736372"),
                Color(id = 8,"Beaver", "#A18276"))),
        Palette(name = "Palette 3",
            colors = listOf(Color(id = 9,"Eggplant", "#52414C"),
                Color(id = 10,"Ebony", "#596157"),
                Color(id = 11,"Middle Green", "#5B8C5A"),
                Color(id = 12,"Green Yellow Crayola", "#CFD186"),
                Color(id = 13,"Fire Opal", "#E3655B"))),
        Palette(name = "Palette 4",
            colors = listOf(Color(id = 14,"Viridian Green", "#0FA3B1"),
                Color(id = 15,"Honeydew", "#D9E5D6"),
                Color(id = 16,"Medium Champagne", "#EDDEA4"),
                Color(id = 17,"Atomic Tangerine", "#F7A072"),
                Color(id = 18,"Deep Saffron", "#FF9B42"))),
        Palette(name = "Palette 5",
            colors = listOf(Color(id = 19,"Bittersweet", "#FF6666"),
                Color(id = 20,"Inchworm", "#CCFF66"),
                Color(id = 21,"Tiffany Blue", "#2EC4B6"),
                Color(id = 22,"Lemon Meringue", "#F1E8B8"))),
        Palette(name = "Palette 1",
            colors = listOf(Color(id = 23,"Palatinate purple", "#5C2751"),
                Color(id = 24,"Liberty", "#6457A6"),
                Color(id = 25,"Maximum Blue Purple", "#9DACFF"),
                Color(id = 26,"Sky Blue Crayola", "#76E5FC"))),
        Palette(name = "Palette 2",
            colors = listOf(Color(id = 27,"Nyanza", "#DCEED1"),
                Color(id = 28,"Cambridge Blue", "#AAC0AA"),
                Color(id = 29,"Old Lavender", "#736372"),
                Color(id = 30,"Beaver", "#A18276"))),
        Palette(name = "Palette 3",
            colors = listOf(Color(id = 31,"Eggplant", "#52414C"),
                Color(id = 32,"Ebony", "#596157"),
                Color(id = 33,"Middle Green", "#5B8C5A"),
                Color(id = 34,"Green Yellow Crayola", "#CFD186"),
                Color(id = 35,"Fire Opal", "#E3655B"))),
        Palette(name = "Palette 4",
            colors = listOf(Color(id = 36,"Viridian Green", "#0FA3B1"),
                Color(id = 37,"Honeydew", "#D9E5D6"),
                Color(id = 38,"Medium Champagne", "#EDDEA4"),
                Color(id = 39,"Atomic Tangerine", "#F7A072"),
                Color(id = 40,"Deep Saffron", "#FF9B42"))),
        Palette(name = "Palette 5",
            colors = listOf(Color(id = 41,"Bittersweet", "#FF6666"),
                Color(id = 42,"Inchworm", "#CCFF66"),
                Color(id = 43,"Tiffany Blue", "#2EC4B6"),
                Color(id = 44,"Lemon Meringue", "#F1E8B8")))
    )
